server:
  port: 8008
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/o2o-store?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: hyxiao
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  resources:
    add-mappings: false # 拒绝了默认404的处理方式
  mvc:
    throw-exception-if-no-handler-found: true

mybatis:
  mapper-locations: classpath:mapping/*.xml
