server:
  port: 8008
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/o2o-store?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: hyxiao
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  resources:
    add-mappings: true # 该值为true，表示如果所有的controller都没有命中，则使用默认的静态资源处理器做匹配
  mvc:
    throw-exception-if-no-handler-found: true
    # 接入前端静态资源页面
    static-path-pattern: /static/**
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    org.apache.ibatis: DEBUG
    java.sql: DEBUG